FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

RUN apk add --no-cache bash

COPY app/ .

RUN chmod +x gradlew && ./gradlew --no-daemon -q help || true

ENV SPRING_PROFILES_ACTIVE=dev
EXPOSE 8000

CMD ["sh","-c","tail -f /dev/null"]