version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Frontend/app:/app
    networks:
      - shared-net

  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./Auth/app:/app
    networks:
      - shared-net

  board:
    build:
      context: ./Board
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./Board/app:/app
    networks:
      - shared-net

  core:
    build:
      context: ./Core
      dockerfile: Dockerfile.dev
    ports:
      - "8003:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./Core/app:/app
    networks:
      - shared-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - shared-net

  nginx:
    build:
      context: ./Nginx
    ports:
      - "80:80"
    networks:
      - shared-net

  # 필요시 Database, Kafka, Messenger 등 추가
  # database:
  #   build:
  #     context: ./Database
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - shared-net

  # kafka:
  #   build:
  #     context: ./Kafka
  #   ports:
  #     - "9092:9092"
  #   networks:
  #     - shared-net

  # messenger:
  #   build:
  #     context: ./Messenger
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - shared-net

networks:
  shared-net:
    driver: overlay