global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['nodeexporter:9100'] 

  - job_name: 'messenger_service' 
    static_configs:
      - targets: ['messenger-service:8000'] 
    metrics_path: '/metrics' 
