version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # 프로메테우스 설정 파일
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - nodeexporter
    networks:
      - shared-net

  grafana:
    image: grafana/grafana
    container_name: grafana_server
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - shared-net



  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_server
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($|/)"'
    restart: unless-stopped
    networks:
      - shared-net

volumes:
  prometheus_data:
  grafana_data:

networks:
  shared-net:
    external: true
    name: shared-net
