version: '3.8'

services:
  core-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8003:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./app:/app
    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: shared-net