FROM python:3.12-slim
WORKDIR /app
COPY app/ /app/
RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN apt-get update && apt-get install -y libglib2.0-0
CMD ["/app/.venv/bin/gunicorn", "-c", "gunicorn_conf.py", "src.main:app"]
