# version: '3.8'

# services:
#   nginx:
#     image: nginx:latest
#     build:
#       context: . 
#       dockerfile: Dockerfile.dev 
#     ports:
#       - "80:80" 
#       - "443:443" 
#     volumes:
      

      
#       - ./app/certbot-www:/var/www/certbot
#       - ./app/certbot-etc:/etc/letsencrypt
     
    
#     restart: always
#     networks:
#       - default

  


# networks:
#   default:
#     external: true
#     name: shared-net
# docker-compose.yml 파일 수정본 (설정 파일 볼륨 추가!)
version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Certbot 관련 볼륨 (이건 그대로!)
      - ./app/certbot-www:/var/www/certbot:z # Certbot 웹루트 경로
      - ./app/certbot-etc:/etc/letsencrypt:z # Certbot 설정 파일 경로

      # ✨ Nginx 설정 파일 볼륨 추가! ✨
      # 호스트의 ./app/nginx/nginx.conf 파일을 컨테이너의 /etc/nginx/nginx.conf 로 연결
      # 네 Nginx 메인 설정 파일이 호스트의 ./app/nginx 폴더 안에 있어야 해!
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:z

      # 호스트의 ./app/nginx/conf.d/ 폴더를 컨테이너의 /etc/nginx/conf.d/ 폴더로 연결
      # 여기에는 사이트별 설정 파일(예: default.conf)들을 넣어두면 좋아!
      # 이 폴더도 호스트의 ./app/nginx 폴더 안에 있어야겠지?
      - ./app/nginx/conf.d/:/etc/nginx/conf.d/:z

    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: shared-net
