version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:

      - ./app/certbot-www:/var/www/certbot:z 
      - ./app/certbot-etc:/etc/letsencrypt:z 
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./app/nginx/conf.d/:/etc/nginx/conf.d/:z

    restart: always
    networks:
      - default