version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6378:6379"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: shared-net